### ISSUE TITLE
Please provide repository branched from official LLVM git mirror

### ISSUE THREAD

**Issue by nanoant** [clang-omp/clang#5] opened 2013-09-08 15:38 UTC
It is nice you provide source code for your changes, however it is completely detached from mainline LLVM code repository itself so it is hard really to track changes or to rebase it onto current LLVM trunk.

Therefore provide Git repo branched either from `https://github.com/llvm-mirror` or `http://llvm.org/git/llvm.git`.

**Comment by clang-omp** [comment] 2013-09-09 11:32
Hi Adam,

Merging OpenMP patch with clang trunk and then keep it constantly updated is a lot of work. We prefer to spend our limited resources into improving OpenMP support itself -- with the goal to eventually commit it into clang trunk.

I know that Chris Bergström from Pathscale planned to integrate OpenMP patch with clang trunk (http://lists.cs.uiuc.edu/pipermail/cfe-dev/2013-August/031608.html) -- you might want to contact him for update.

**Comment by tycho** [comment] 2013-09-13 11:38
nanoant: I've imported Intel's patches into my own repo (forked from LLVM's official git mirrors) on a branch named 'openmp', if it helps at all.

http://git.uplinklabs.net/snoonan/llvm/clang.git/log/?h=openmp

**Comment by nanoant** [comment] 2013-09-13 12:23
Awesome, thank @tycho ! This is what I was asking about.

@clang-omp It wasn't my intent to request rebasing and updating OpenMP from your side onto latest trunk (master), but just providing original branching source (SHA1) so I can rebase it myself and find the diverge point.

**Comment by tycho** [comment] 2013-09-14 21:44
@nanoant: Glad it helps -- by the way, I just did a long overdue cleanup of my git server, so it was relocated to [here](http://git.uplinklabs.net/snoonan/projects/llvm/clang.git/log/?h=openmp) (but any existing clones should still be able to pull from the old URL).

**Comment by clang-omp** [comment] 2013-09-30 10:11
As I understand, the issue is resolved (thanks, tycho!)

I'm closing it.

**Closed as completed by clang-omp** 2013-09-30 10:11 UTC
Labels: question
