### ISSUE TITLE
random access iterators are not correctly detected

### ISSUE THREAD

**Issue by serge-sans-paille** [clang-omp/clang#3] opened 2013-08-31 14:56 UTC
In the following code, `xrange_iterator` is a random access iterator but clang++ states the opposite _because of the `auto` keyword_.

Turning `auto` into `xrange_iterator` solves the issue. The same problem happen when the type of the index variable comes from a nested type specifier (`typename foo<T>::bar` or from a `decltype`

```
#include <iterator>
#include <algorithm>

/* xrange */
struct xrange_iterator : std::iterator< std::random_access_iterator_tag, long >{
            long value;
            long step;
            long sign;
            xrange_iterator() {}
            xrange_iterator(long v, long s) : value(v), step(s), sign(s<0?-1:1) {}
            long operator*() const { return value; }
            long operator[](long n) const { return value + step *n; }
            xrange_iterator& operator++() { value+=step; return *this; }
            xrange_iterator operator++(int) { xrange_iterator self(*this); value+=step; return self; }
            xrange_iterator& operator+=(long n) { value+=step*n; return *this; }
            xrange_iterator& operator--() { value-=step; return *this; }
            xrange_iterator operator--(int) { xrange_iterator self(*this); value-=step; return self; }
            xrange_iterator& operator-=(long n) { value-=step*n; return *this; }
            bool operator!=(xrange_iterator const& other) const { return value != other.value; }
            bool operator==(xrange_iterator const& other) const { return value == other.value; }
            bool operator<(xrange_iterator const& other) const { return sign*value < sign*other.value; }
            bool operator<=(xrange_iterator const& other) const { return sign*value <= sign*other.value; }
            bool operator>(xrange_iterator const& other) const { return sign*value > sign*other.value; }
            bool operator>=(xrange_iterator const& other) const { return sign*value >= sign*other.value; }
            long operator-(xrange_iterator const& other) const { return (value - other.value)/step; }
        };

        struct xrange {
            long _begin;
            long _end;
            long _step;
            long _last;
            typedef long value_type;
            typedef xrange_iterator iterator;
            typedef xrange_iterator const_iterator;
            void _init_last() {
                if(_step>0) _last= _begin + std::max(0L,_step * ( (_end - _begin + _step -1)/ _step));
                else _last= _begin + std::min(0L,_step * ( (_end - _begin + _step +1)/ _step)) ;
            }
            xrange(){}
            xrange( long b, long e , long s=1) : _begin(b), _end(e), _step(s) { _init_last(); }
            xrange( long e ) : _begin(0), _end(e), _step(1) { _init_last(); }
            xrange_iterator begin() const { return xrange_iterator(_begin, _step); }
            xrange_iterator end() const { return xrange_iterator(_last, _step); }
        };
#include<iostream>
#include <omp.h>

int main() {
   xrange r(1000000);
#pragma omp parallel for
   for(auto b = r.begin(); b < r.end() ; ++b)
       std::cout << omp_get_thread_num() << ":" << *b* *b * *b << "\n";
   return 0;
}
```

**Comment by alexey-bataev** [comment] 2013-09-02 02:39
Serge, thanks for the report. Will be fixed soon.
Best regards,
Alexey Bataev

**Comment by alexey-bataev** [comment] 2013-09-02 03:28
Serge, I can't reproduce this bug.
I successfully compiled this code without any warnings or errors.

clang++ -fopenmp bug4.cpp -std=c++0x

What options did you used for the compilation? Did you tried to update to latest version?

**Comment by serge-sans-paille** [comment] 2013-09-02 07:04
strange enough:

```
/home/serge/tmp/llvm/bin/clang++ -I ~/sources/libomp_oss/exports/common/include -L ~/sources/libomp_oss/exports/lin_32e/lib/  -fopenmp -std=c++0x a.cc -o a
```

master branch of llvm, clang-omp branch for clang ...

all branches pulled this morning

**Comment by alexey-bataev** [comment] 2013-09-02 07:06
And what is the result?

**Comment by alexey-bataev** [comment] 2013-09-02 07:24
Tried on Linux too, but still no errors or warnings, the code is compiled successfully.

**Comment by serge-sans-paille** [comment] 2013-09-02 08:12
```
a.cc:52:13: error: iteration variable is not of a random access iterator type
   for(auto b = r.begin(); b < r.end() ; ++b)
```

**Comment by serge-sans-paille** [comment] 2013-09-02 08:13
```
serge@lakota:/tmp$ /home/serge/tmp/llvm/bin/clang++ --version
clang version 3.3 (https://github.com/clang-omp/clang 58eb68275f3f08c6d867e6f2f9ccbcc8e6226893) (https://github.com/clang-omp/llvm 2451bcb58b76866f4350145a34f446c295321f58)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

**Comment by alexey-bataev** [comment] 2013-09-02 08:28
Serge, may I ask to prepare preprocessed source file and to send it to me? Cause I still can't reproduce this problem. And I need preprocessed code to investigate the problem.

**Comment by serge-sans-paille** [comment] 2013-09-02 08:38
http://ridee.enstb.org/sguelton/a.cc.preprocessed

**Comment by alexey-bataev** [comment] 2013-09-02 08:46
Serge, thank you. Now I see this error report.

**Comment by serge-sans-paille** [comment] 2013-09-02 08:53
Great! Thanks alexey for the quick answers!

**Comment by alexey-bataev** [comment] 2013-09-02 09:15
Serge, try the latest version.

**Comment by serge-sans-paille** [comment] 2013-09-02 09:54
Works nice!
I'll give a try to more complex examples soon ;-)

**Comment by alexey-bataev** [comment] 2013-09-02 09:55
Good! :+1: 
Closing it for now.
Best regards,
Alexey Bataev

**Closed as completed by alexey-bataev** 2013-09-02 09:55 UTC
Labels: bug
